// Generated by scripts/prepare-character-artwork.py; edit scripts/character-artwork.json.
export const CHAMPIONS = [
  {
    "id": "jinx",
    "name": "Jinx",
    "artwork": "Arcane Fractured Jinx",
    "image": "/media/characters/jinx-480.webp",
    "srcSet": "/media/characters/jinx-240.webp 240w, /media/characters/jinx-480.webp 480w",
    "wide": "/media/characters/jinx-wide.webp",
    "thumbnail": "/media/characters/jinx-thumb.webp"
  },
  {
    "id": "vi",
    "name": "Vi",
    "artwork": "Arcane Brawler Vi",
    "image": "/media/characters/vi-480.webp",
    "srcSet": "/media/characters/vi-240.webp 240w, /media/characters/vi-480.webp 480w",
    "wide": "/media/characters/vi-wide.webp",
    "thumbnail": "/media/characters/vi-thumb.webp"
  },
  {
    "id": "ekko",
    "name": "Ekko",
    "artwork": "Arcane Last Stand Ekko",
    "image": "/media/characters/ekko-480.webp",
    "srcSet": "/media/characters/ekko-240.webp 240w, /media/characters/ekko-480.webp 480w",
    "wide": "/media/characters/ekko-wide.webp",
    "thumbnail": "/media/characters/ekko-thumb.webp"
  },
  {
    "id": "jayce",
    "name": "Jayce",
    "artwork": "Arcane Survivor Jayce",
    "image": "/media/characters/jayce-480.webp",
    "srcSet": "/media/characters/jayce-240.webp 240w, /media/characters/jayce-480.webp 480w",
    "wide": "/media/characters/jayce-wide.webp",
    "thumbnail": "/media/characters/jayce-thumb.webp"
  },
  {
    "id": "caitlyn",
    "name": "Caitlyn",
    "artwork": "Arcane Commander Caitlyn",
    "image": "/media/characters/caitlyn-480.webp",
    "srcSet": "/media/characters/caitlyn-240.webp 240w, /media/characters/caitlyn-480.webp 480w",
    "wide": "/media/characters/caitlyn-wide.webp",
    "thumbnail": "/media/characters/caitlyn-thumb.webp"
  },
  {
    "id": "viktor",
    "name": "Viktor",
    "artwork": "Arcane Savior Viktor",
    "image": "/media/characters/viktor-480.webp",
    "srcSet": "/media/characters/viktor-240.webp 240w, /media/characters/viktor-480.webp 480w",
    "wide": "/media/characters/viktor-wide.webp",
    "thumbnail": "/media/characters/viktor-thumb.webp"
  },
  {
    "id": "mel",
    "name": "Mel",
    "artwork": "Arcane Councilor Mel",
    "image": "/media/characters/mel-480.webp",
    "srcSet": "/media/characters/mel-240.webp 240w, /media/characters/mel-480.webp 480w",
    "wide": "/media/characters/mel-wide.webp",
    "thumbnail": "/media/characters/mel-thumb.webp"
  },
  {
    "id": "heimerdinger",
    "name": "Heimerdinger",
    "artwork": "Arcane Professor Heimerdinger",
    "image": "/media/characters/heimerdinger-480.webp",
    "srcSet": "/media/characters/heimerdinger-240.webp 240w, /media/characters/heimerdinger-480.webp 480w",
    "wide": "/media/characters/heimerdinger-wide.webp",
    "thumbnail": "/media/characters/heimerdinger-thumb.webp"
  },
  {
    "id": "warwick",
    "name": "Warwick",
    "artwork": "Arcane Vander Warwick",
    "image": "/media/characters/warwick-480.webp",
    "srcSet": "/media/characters/warwick-240.webp 240w, /media/characters/warwick-480.webp 480w",
    "wide": "/media/characters/warwick-wide.webp",
    "thumbnail": "/media/characters/warwick-thumb.webp"
  },
  {
    "id": "singed",
    "name": "Singed",
    "artwork": "Arcane Shimmer Lab Singed",
    "image": "/media/characters/singed-480.webp",
    "srcSet": "/media/characters/singed-240.webp 240w, /media/characters/singed-480.webp 480w",
    "wide": "/media/characters/singed-wide.webp",
    "thumbnail": "/media/characters/singed-thumb.webp"
  }
];
