"""Fetch official splash art and build local WebP variants. Requires Pillow (see requirements-artwork.txt)."""
import hashlib
import io
import json
from pathlib import Path
from urllib.request import Request, urlopen

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "scripts/character-artwork.json"
CACHE = ROOT / "node_modules/.cache/arcane-artwork"
OUTPUT = ROOT / "public/media/characters"


def fetch_artwork(character, base):
    source = f"{base}{character['champion']}_{character['skin']}.jpg"
    cached = CACHE / f"{character['champion']}.jpg"
    if cached.exists():
        data = cached.read_bytes()
    else:
        request = Request(source, headers={"User-Agent": "ArcaneArtworkPreparation/1.0"})
        with urlopen(request, timeout=30) as response:
            if response.headers.get_content_type() != "image/jpeg":
                raise ValueError(f"Expected JPEG artwork for {character['name']}")
            data = response.read(10_000_001)
        if len(data) > 10_000_000:
            raise ValueError(f"Artwork exceeds download limit: {character['name']}")
    image = Image.open(io.BytesIO(data))
    image.load()
    if image.width < 1000 or image.height < 660:
        raise ValueError(f"Source too small for approved crop: {character['name']}")
    cached.write_bytes(data)
    return image.convert("RGB"), source, hashlib.sha256(data).hexdigest()


def main():
    config = json.loads(CONFIG.read_text())
    CACHE.mkdir(parents=True, exist_ok=True)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest = []
    for character in config["characters"]:
        image, source, checksum = fetch_artwork(character, config["sourceBase"])
        left, top, right, bottom = character["crop"]
        if not (0 <= left < right <= image.width and 0 <= top < bottom <= image.height):
            raise ValueError(f"Crop out of bounds: {character['name']}")
        portrait = image.crop((left, top, right, bottom))
        if portrait.width * 4 != portrait.height * 3:
            raise ValueError(f"Portrait must be 3:4: {character['name']}")
        slug = character["id"]
        for width in (240, 480):
            portrait.resize((width, width * 4 // 3), Image.Resampling.LANCZOS).save(
                OUTPUT / f"{slug}-{width}.webp", quality=85, method=6
            )
        # Preserve the complete composition for future motion graphics; never upscale.
        image.save(OUTPUT / f"{slug}-wide.webp", quality=85, method=6)
        # Face-focused square thumbnail derived from the approved portrait's upper section.
        side = portrait.width
        portrait.crop((0, 0, side, side)).resize((160, 160), Image.Resampling.LANCZOS).save(
            OUTPUT / f"{slug}-thumb.webp", quality=85, method=6
        )
        manifest.append({
            **character,
            "image": f"/media/characters/{slug}-480.webp",
            "srcSet": f"/media/characters/{slug}-240.webp 240w, /media/characters/{slug}-480.webp 480w",
            "wide": f"/media/characters/{slug}-wide.webp",
            "thumbnail": f"/media/characters/{slug}-thumb.webp",
            "source": source,
            "sourceSha256": checksum,
            "sourceWidth": image.width,
            "sourceHeight": image.height,
        })
        print(f"Prepared {character['name']}: portrait 240/480, wide, thumbnail")
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    runtime_fields = ("id", "name", "artwork", "image", "srcSet", "wide", "thumbnail")
    runtime = [{key: item[key] for key in runtime_fields} for item in manifest]
    (ROOT / "src/lib/characters.js").write_text(
        "// Generated by scripts/prepare-character-artwork.py; edit scripts/character-artwork.json.\n"
        "export const CHAMPIONS = " + json.dumps(runtime, indent=2) + ";\n"
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        raise SystemExit(f"Artwork preparation failed: {error}") from error
